name: doc_coverage
description: Analyze the quality of your package's public documentation.
dependencies:
  args: any
  browser: any
  html: '>=0.12.0 <0.13.0'
  route: any
dev_dependencies:
  unittest: '>=0.11.0'
